name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Hi, We are working on desktop PC with GeForce RTX 2070 '' first issue'
        pr-message: 'Welcome new users'' first pr'
